export const TRADES = [
  "Electrician",
  "Plumber",
  "Carpenter",
  "Painter",
  "Mason",
  "Roofer",
  "Tiler",
  "Plasterer",
  "HVAC Technician",
  "Welder",
  "Locksmith",
  "Gardener / Landscaper",
  "Cleaner",
  "Mover",
  "Appliance Repair Technician",
  "Handyman",
  "Glazier",
  "Flooring Installer",
  "Pool Maintenance",
  "Pest Control",
  "Solar Panel Installer",
  "Blacksmith",
  "Upholsterer",
  "Auto Mechanic",
  "Tailor",
];
